# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/max/Desktop/AppAnvil-merged

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/max/Desktop/AppAnvil-merged

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/Desktop/AppAnvil-merged/CMakeFiles /home/max/Desktop/AppAnvil-merged/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/Desktop/AppAnvil-merged/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named appanvil

# Build rule for target.
appanvil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appanvil
.PHONY : appanvil

# fast build rule for target.
appanvil/fast:
	$(MAKE) -f CMakeFiles/appanvil.dir/build.make CMakeFiles/appanvil.dir/build
.PHONY : appanvil/fast

#=============================================================================
# Target rules for targets named appanvil_main

# Build rule for target.
appanvil_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appanvil_main
.PHONY : appanvil_main

# fast build rule for target.
appanvil_main/fast:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/build
.PHONY : appanvil_main/fast

#=============================================================================
# Target rules for targets named FORMAT

# Build rule for target.
FORMAT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FORMAT
.PHONY : FORMAT

# fast build rule for target.
FORMAT/fast:
	$(MAKE) -f CMakeFiles/FORMAT.dir/build.make CMakeFiles/FORMAT.dir/build
.PHONY : FORMAT/fast

#=============================================================================
# Target rules for targets named aa-caller

# Build rule for target.
aa-caller: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aa-caller
.PHONY : aa-caller

# fast build rule for target.
aa-caller/fast:
	$(MAKE) -f aa-caller/CMakeFiles/aa-caller.dir/build.make aa-caller/CMakeFiles/aa-caller.dir/build
.PHONY : aa-caller/fast

resources/resource.autogen.o: resources/resource.autogen.c.o

.PHONY : resources/resource.autogen.o

# target to build an object file
resources/resource.autogen.c.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/resources/resource.autogen.c.o
.PHONY : resources/resource.autogen.c.o

resources/resource.autogen.i: resources/resource.autogen.c.i

.PHONY : resources/resource.autogen.i

# target to preprocess a source file
resources/resource.autogen.c.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/resources/resource.autogen.c.i
.PHONY : resources/resource.autogen.c.i

resources/resource.autogen.s: resources/resource.autogen.c.s

.PHONY : resources/resource.autogen.s

# target to generate assembly for a file
resources/resource.autogen.c.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/resources/resource.autogen.c.s
.PHONY : resources/resource.autogen.c.s

src/console_thread.o: src/console_thread.cc.o

.PHONY : src/console_thread.o

# target to build an object file
src/console_thread.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/console_thread.cc.o
.PHONY : src/console_thread.cc.o

src/console_thread.i: src/console_thread.cc.i

.PHONY : src/console_thread.i

# target to preprocess a source file
src/console_thread.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/console_thread.cc.i
.PHONY : src/console_thread.cc.i

src/console_thread.s: src/console_thread.cc.s

.PHONY : src/console_thread.s

# target to generate assembly for a file
src/console_thread.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/console_thread.cc.s
.PHONY : src/console_thread.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/appanvil.dir/build.make CMakeFiles/appanvil.dir/src/main.cc.o
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/appanvil.dir/build.make CMakeFiles/appanvil.dir/src/main.cc.i
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/appanvil.dir/build.make CMakeFiles/appanvil.dir/src/main.cc.s
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/main_window.o: src/main_window.cc.o

.PHONY : src/main_window.o

# target to build an object file
src/main_window.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/main_window.cc.o
.PHONY : src/main_window.cc.o

src/main_window.i: src/main_window.cc.i

.PHONY : src/main_window.i

# target to preprocess a source file
src/main_window.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/main_window.cc.i
.PHONY : src/main_window.cc.i

src/main_window.s: src/main_window.cc.s

.PHONY : src/main_window.s

# target to generate assembly for a file
src/main_window.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/main_window.cc.s
.PHONY : src/main_window.cc.s

src/tabs/about.o: src/tabs/about.cc.o

.PHONY : src/tabs/about.o

# target to build an object file
src/tabs/about.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/about.cc.o
.PHONY : src/tabs/about.cc.o

src/tabs/about.i: src/tabs/about.cc.i

.PHONY : src/tabs/about.i

# target to preprocess a source file
src/tabs/about.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/about.cc.i
.PHONY : src/tabs/about.cc.i

src/tabs/about.s: src/tabs/about.cc.s

.PHONY : src/tabs/about.s

# target to generate assembly for a file
src/tabs/about.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/about.cc.s
.PHONY : src/tabs/about.cc.s

src/tabs/file_chooser.o: src/tabs/file_chooser.cc.o

.PHONY : src/tabs/file_chooser.o

# target to build an object file
src/tabs/file_chooser.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/file_chooser.cc.o
.PHONY : src/tabs/file_chooser.cc.o

src/tabs/file_chooser.i: src/tabs/file_chooser.cc.i

.PHONY : src/tabs/file_chooser.i

# target to preprocess a source file
src/tabs/file_chooser.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/file_chooser.cc.i
.PHONY : src/tabs/file_chooser.cc.i

src/tabs/file_chooser.s: src/tabs/file_chooser.cc.s

.PHONY : src/tabs/file_chooser.s

# target to generate assembly for a file
src/tabs/file_chooser.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/file_chooser.cc.s
.PHONY : src/tabs/file_chooser.cc.s

src/tabs/processes.o: src/tabs/processes.cc.o

.PHONY : src/tabs/processes.o

# target to build an object file
src/tabs/processes.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/processes.cc.o
.PHONY : src/tabs/processes.cc.o

src/tabs/processes.i: src/tabs/processes.cc.i

.PHONY : src/tabs/processes.i

# target to preprocess a source file
src/tabs/processes.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/processes.cc.i
.PHONY : src/tabs/processes.cc.i

src/tabs/processes.s: src/tabs/processes.cc.s

.PHONY : src/tabs/processes.s

# target to generate assembly for a file
src/tabs/processes.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/processes.cc.s
.PHONY : src/tabs/processes.cc.s

src/tabs/profiles.o: src/tabs/profiles.cc.o

.PHONY : src/tabs/profiles.o

# target to build an object file
src/tabs/profiles.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/profiles.cc.o
.PHONY : src/tabs/profiles.cc.o

src/tabs/profiles.i: src/tabs/profiles.cc.i

.PHONY : src/tabs/profiles.i

# target to preprocess a source file
src/tabs/profiles.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/profiles.cc.i
.PHONY : src/tabs/profiles.cc.i

src/tabs/profiles.s: src/tabs/profiles.cc.s

.PHONY : src/tabs/profiles.s

# target to generate assembly for a file
src/tabs/profiles.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/profiles.cc.s
.PHONY : src/tabs/profiles.cc.s

src/tabs/status.o: src/tabs/status.cc.o

.PHONY : src/tabs/status.o

# target to build an object file
src/tabs/status.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/status.cc.o
.PHONY : src/tabs/status.cc.o

src/tabs/status.i: src/tabs/status.cc.i

.PHONY : src/tabs/status.i

# target to preprocess a source file
src/tabs/status.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/status.cc.i
.PHONY : src/tabs/status.cc.i

src/tabs/status.s: src/tabs/status.cc.s

.PHONY : src/tabs/status.s

# target to generate assembly for a file
src/tabs/status.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/status.cc.s
.PHONY : src/tabs/status.cc.s

src/tabs/status_column_record.o: src/tabs/status_column_record.cc.o

.PHONY : src/tabs/status_column_record.o

# target to build an object file
src/tabs/status_column_record.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/status_column_record.cc.o
.PHONY : src/tabs/status_column_record.cc.o

src/tabs/status_column_record.i: src/tabs/status_column_record.cc.i

.PHONY : src/tabs/status_column_record.i

# target to preprocess a source file
src/tabs/status_column_record.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/status_column_record.cc.i
.PHONY : src/tabs/status_column_record.cc.i

src/tabs/status_column_record.s: src/tabs/status_column_record.cc.s

.PHONY : src/tabs/status_column_record.s

# target to generate assembly for a file
src/tabs/status_column_record.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/tabs/status_column_record.cc.s
.PHONY : src/tabs/status_column_record.cc.s

src/threads/command_caller.o: src/threads/command_caller.cc.o

.PHONY : src/threads/command_caller.o

# target to build an object file
src/threads/command_caller.cc.o:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/threads/command_caller.cc.o
.PHONY : src/threads/command_caller.cc.o

src/threads/command_caller.i: src/threads/command_caller.cc.i

.PHONY : src/threads/command_caller.i

# target to preprocess a source file
src/threads/command_caller.cc.i:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/threads/command_caller.cc.i
.PHONY : src/threads/command_caller.cc.i

src/threads/command_caller.s: src/threads/command_caller.cc.s

.PHONY : src/threads/command_caller.s

# target to generate assembly for a file
src/threads/command_caller.cc.s:
	$(MAKE) -f CMakeFiles/appanvil_main.dir/build.make CMakeFiles/appanvil_main.dir/src/threads/command_caller.cc.s
.PHONY : src/threads/command_caller.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... uninstall"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... appanvil"
	@echo "... edit_cache"
	@echo "... appanvil_main"
	@echo "... install/local"
	@echo "... FORMAT"
	@echo "... aa-caller"
	@echo "... resources/resource.autogen.o"
	@echo "... resources/resource.autogen.i"
	@echo "... resources/resource.autogen.s"
	@echo "... src/console_thread.o"
	@echo "... src/console_thread.i"
	@echo "... src/console_thread.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main_window.o"
	@echo "... src/main_window.i"
	@echo "... src/main_window.s"
	@echo "... src/tabs/about.o"
	@echo "... src/tabs/about.i"
	@echo "... src/tabs/about.s"
	@echo "... src/tabs/file_chooser.o"
	@echo "... src/tabs/file_chooser.i"
	@echo "... src/tabs/file_chooser.s"
	@echo "... src/tabs/processes.o"
	@echo "... src/tabs/processes.i"
	@echo "... src/tabs/processes.s"
	@echo "... src/tabs/profiles.o"
	@echo "... src/tabs/profiles.i"
	@echo "... src/tabs/profiles.s"
	@echo "... src/tabs/status.o"
	@echo "... src/tabs/status.i"
	@echo "... src/tabs/status.s"
	@echo "... src/tabs/status_column_record.o"
	@echo "... src/tabs/status_column_record.i"
	@echo "... src/tabs/status_column_record.s"
	@echo "... src/threads/command_caller.o"
	@echo "... src/threads/command_caller.i"
	@echo "... src/threads/command_caller.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

